### ISSUE TITLE
[RESOLVED] After 3rd Party App Upgrade, graphic elements in WebUI are lost, raw version of nextcloud is show

### ISSUE THREAD

**Issue by frankmaszinek** [e-alfred/nextcloud-printer#14] opened 2020-12-20 14:56 UTC
The culprit was the Printer App. It had to be manually disabled. The app is a 3rd party app and was causing Nextcloud WebUI to crash. Nextcloud itself, but the WebUI doesn't display the theme. What you get instead is a bunch of raw text on the screen with buttons that don't easily navigate anywhere. For example, while you could load up Nextcloud, you couldn't navigate Settings or Apps to disable or reconfigure anything. At least it didn't appear to be so in raw format.

So the OCC command was needed in /var/www/nextcloud directory to disable the printer app.

sudo -u www-data php ./occ app:disable printer

Credit is given to this thread for identifying the concern about 3rd party apps and indicating that individually disabling 3rd party apps may work.

https://help.nextcloud.com/t/resolved-after-upgrade-nc-to-v17-graphic-elements-in-webui-are-lost-raw-version-of-nextcloud-is-show/61626 ↗

LESSON LEARNED. Don't install any unofficial Nextcloud apps.  I will be removing any 3rd party apps from the system from here on out.

**Comment by kesselb** [comment] 2020-12-20 15:00
This report is actually a duplicate of https://github.com/e-alfred/nextcloud-printer/issues/13

**Comment by e-alfred** [comment] 2020-12-21 22:28
Sorry for the inconvenience, this is fixed by version 0.0.5. I removed the problematic release.

**Closed as completed** 2020-12-21 22:30 UTC
Labels: duplicate
